spring:
  application:
    name: order
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
server:
  port: 18082
#item:
  #ribbon:
    #NFLoadBalancerClassName: com.netflix.loadbalancer.RoundRobinRule #轮询
    # NFLoadBalancerClassName: com.netflix.loadbalancer.RandomRule 随机
    # NFLoadBalancerClassName: com.netflix.loadbalancer.RetryRule 重试
    # NFLoadBalancerClassName: com.netflix.loadbalancer.ZoneAvoidanceRule 加权法
feign:
  client:
    config:
      default: # default指定的是所有的feign客户端 都设置为该配置超时时间
        connectionTimeout: 5000 # 链接超时时间
        readTimeout: 5000 # 读取超时时间