spring:
  redis:
    port: 6379
    host: localhost
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/itcast_mp?useSSL=false
      username: root
      password: root
server:
  port: 81
mybatis:
  mapper-locations: classpath*:mappers/*Mapper.xml
                          # 第一个*:所有类路径下,所有的jar下  会扫所有的jar包,一般不加
  type-aliases-package: com.itheima.pojo
logging:
  pattern:
    # 在控制台打印
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %msg - %logger{15}%n\'
  level:
    root: info
    com:
      itheima: debug
  file: /Users/chris/tanhua
    max-size: 10