server:
  port: 18083
  # 配置redis
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/itcast_tanhua_manage?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true&useSSL=false
    username: root
    password: root
  redis:
    host: localhost
    port: 6379
dubbo:
  consumer:
    check: false
  application:
    name: tanhua-manage
  registry:
    address: zookeeper://127.0.0.1:2181
# 配置短信平台信息
tanhua:
  secret: 76bd425b6f29f7fcc2e0bfc286043df1
  redisValidateCodeKeyPrefix: VALIDATECODE_
  sms:
    signName: 黑马程序员
    parameterName: code
    validateCodeTemplateCode: SMS_164508533
    accessKeyId: LTAI5tDRHQk6hfL9JWTcDpWo
    accessKeySecret: UP9EpSxxSYWcMLNpdBSYMW1keEkdL3
  oss:
    endpoint: oss-cn-shenzhen.aliyuncs.com
    accessKeyId: LTAI5tSc4SxGdecXkyp83Xdy
    accessKeySecret: I8SYcHpOjlM96Pxi9o9yDtQRy4UTIn
    bucketName: tanhua-group1
    url: tanhua-group1.oss-cn-shenzhen.aliyuncs.com
  face:
    appId: 24535700
    apiKey: jVcVDuwFLMV3fwU6YcuTMXws
    secretKey: hi6NEeT1hjn3fp6ESc7RdvCYc5jVUGyc
  huanxin:
    url: http://a1.easemob.com/
    orgName: 1102210712041873
    appName: demo
    clientId: YXA6whUHFhr8TR-IqJr_jbfNDw
    clientSecret: YXA6pJvq7AVlR00PnhhuuSZZ3Wo8Ftk
  huawei:
    username: a634716796
    # password: AZTPO64AXEYOQPHNTLN
    password: lili1234
    project: cn-east-3
    domain: hw_008613316915805_01
    # 图片检测内容 politics：是否涉及政治人物的检测，terrorism：是否包含涉政暴恐元素的检测，porn：是否包含涉黄内容元素的检测，ad：是否包含广告的检测（公测特性），all：包含politics、terrorism和porn三种场景的检测
    categoriesImage: politics,terrorism,porn
    # 文字检测内容 politics：涉政，porn：涉黄，ad：广告，abuse：辱骂，contraband：违禁品，flood：灌水
    categoriesText: politics,porn,ad,abuse,contraband,flood
    textApiUrl: https://moderation.cn-east-3.myhuaweicloud.com/v1.0/moderation/text
    imageApiUrl: https://moderation.cn-east-3.myhuaweicloud.com/v1.0/moderation/image/batch
# mybatis-plus
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      table-prefix: tb_
  mapper-locations: classpath*:mapper/*Mapper.xml
# RocketMQ
rocketmq:
  name-server: 127.0.0.1:9876
