spring:
  datasource:
    url: jdbc:mysql://localhost:3306/itcast_tanhuahua?useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/tanhua
mybatis-plus:
  global-config:
    db-config:
      table-prefix: tb_
      id-type: auto
dubbo:
  registry:
    address: zookeeper://127.0.0.1:2181
  scan:
    base-packages: com.tanhua.dubbo.api
  provider:
    timeout: 60000
  application:
    name: dubbo-service
