spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/itcast_tanhuahua?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true&useSSL=false
    username: root
    password: root
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: tanhua
      # url: mongodb://127.0.0.1:27017/tanhua
dubbo:
  registry:
    address: zookeeper://127.0.0.1:2181
  application:
    name: tanhua-dubbo-service
  scan:
    base-packages: com.tanhua.dubbo.api
  provider:
    timeout: 60000
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      table-prefix: tb_
  mapper-locations: classpath*:/mappers/*Mapper.xml
  type-aliases-package: com.tanhua.domain.db
logging:
  level:
    root: info
    com:
      tanhua: debug
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %msg - %logger{15}%n\'