dubbo:
  application:
    name: dubbo-consumer
  registry:
    address: zookeeper://127.0.0.1:2181
  consumer:
    check: false
tanhua:
  sms:
    signName: 黑马程序员
    parameterName: code
    validateCodeTemplateCode: SMS_164508533
    accessKeyId: LTAI5tDRHQk6hfL9JWTcDpWo
    accessKeySecret: UP9EpSxxSYWcMLNpdBSYMW1keEkdL3
  redisValidateCodeKeyPrefix: VALIDATECODE_
  secret: 76bd425b6f29f7fcc2e0bfc286043df1
  oss:
    endpoint: oss-cn-shenzhen.aliyuncs.com
    accessKeyId: LTAI5tSc4SxGdecXkyp83Xdy
    accessKeySecret: I8SYcHpOjlM96Pxi9o9yDtQRy4UTIn
    bucketName: tanhua-group1
    url: tanhua-group1.oss-cn-shenzhen.aliyuncs.com
  face:
    appId: 24535700
    apiKey: jVcVDuwFLMV3fwU6YcuTMXws
    secretKey: hi6NEeT1hjn3fp6ESc7RdvCYc5jVUGyc
# =========================================
# 分布式文件系统FDFS配置
# =========================================
fdfs:
  so-timeout: 1500 #读取时间
  connect-timeout: 600 #连接超时时间
  # 缩略图生成参数
  thumb-image:
    width: 150
    height: 150
  # TrackerList参数,支持多个
  tracker-list: 127.0.0.1:22122
  web-server-url: http://127.0.0.1:9999