spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///itcast_dubbo?useSSL=false
    password: root
    username: root
dubbo:
  registry:
    address: zookeeper://127.0.0.1:2181
  application:
    name: dubbo-provider
  scan:
    base-packages: com.itheima.api
  protocol:
    name: dubbo
    port: 20880
logging:
  level:
    root: info
    com:
      itheima: debug
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %msg - %logger{15}%n\'
